version: '3'

services:
  web:
    image: mdnservice_web
    ports:
      - "9616:9616"
    networks:
      - back-tier
    volumes:
      - /code
    environment:
      - HOST_IP=${HOST_IP}
      - REDIS_HOST_IP=${REDIS_HOST_IP}
      - ETCD_HOST_IP=${ETCD_HOST_IP}
      - SERVICE_NAME=MdnService
      - STAGE=${STAGE}
      - CONFIG_HOST=${CONFIG_HOST}
      - CONFIG_PORT=${CONFIG_PORT}
      - INTERLOCK_DATA={"hostname":"mdn", "domain":"digitalfunk.io"}
    extra_hosts:
      - "cdsp.digitalfunk.io:${HOST_IP}"
      - "etcd.digitalfunk.io:${ETCD_HOST_IP}"
      - "redis.digitalfunk.io:${REDIS_HOST_IP}" 
networks:
    back-tier:
        external: true